name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    services:
      nvector-test-api:
        image: ghcr.io/ezzatron/nvector-test-api
        ports:
          - 17357:8000

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: make link-dependencies

      - name: Make
        run: make ci

      - name: Publish coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
