name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish package

    permissions:
      contents: read
      id-token: write

    services:
      nvector-test-api:
        image: ghcr.io/ezzatron/nvector-test-api
        ports:
          - 17357:8000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: make link-dependencies

      - name: Make
        run: make ci

      - name: Set package version
        run: make set-package-version

      - name: Publish package
        if: success()
        run: |
          npm publish --provenance --access public
          npx --yes jsr publish --allow-dirty
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
